language: erlang
otp_release:
  - 19.3
  - 20.3.8
notifications:
  email:
    - maxim@synrc.com
    - doxtop@synrc.com
script:
  - "curl -fsSL https://raw.github.com/synrc/mad/master/mad > mad"
  - "chmod +x mad"
  - "./mad dep com"
  - "rm -rf deps"
  - "rebar get-deps clean compile"
